// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package landingpage2

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Define the main page layout
func Show() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en\"><body className=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`font-sans antialiased`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/landingpage2/landing_page_2.templ`, Line: 6, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div class=\"min-h-screen flex flex-col\"><main class=\"flex-1 flex items-center justify-center px-4 py-12 md:py-20\"><div class=\"w-full max-w-7xl mx-auto grid md:grid-cols-2 gap-12 md:gap-16 items-center\"><div class=\"flex justify-center mx-auto md:justify-end order-2 md:order-1\"><div class=\"relative\"><div class=\"relative w-[280px] h-[570px] bg-primary rounded-[3rem] p-3 shadow-2xl\"><div class=\"w-full h-full bg-background rounded-[2.5rem] overflow-hidden\"><div class=\"h-full bg-card\"><img src=\"/women-s-clothing-app-interface-showing-dresses-col.jpg\" alt=\"App Preview\" class=\"w-full h-full object-cover\"></div></div><div class=\"absolute top-6 left-1/2 -translate-x-1/2 w-24 h-6 bg-primary rounded-full\"></div></div></div></div><div class=\"space-y-6 md:space-y-8 order-1 md:order-2 text-center md:text-left flex flex-col items-center md:items-start\"><div class=\"space-y-4\"><h1 class=\"text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-balance\">Your Style, Delivered</h1><p class=\"text-lg md:text-xl text-muted-foreground max-w-lg mx-auto md:mx-0 text-pretty leading-relaxed\">Discover the latest women's fashion trends and shop curated collections tailored just for you. Fashion has never been this effortless.</p></div><div class=\"flex flex-col sm:flex-row gap-4 justify-center md:justify-start pt-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AppStoreBadge().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = GooglePlayBadge().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div></main></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
