// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"alternate\" hreflang=\"en\" href=\"https://classic-shop.ly/en\"><link rel=\"alternate\" hreflang=\"ar\" href=\"https://classic-shop.ly/ar\"><link rel=\"alternate\" hreflang=\"x-default\" href=\"https://classic-shop.ly/en\"><title>Classic</title><script defer src=\"/assets/js/cdn.min.js\"></script><script>\r\n        // 1. Theme Logic: Apply 'dark' class immediately\r\n        (function() {\r\n            const theme = localStorage.getItem('theme');\r\n            if (theme === 'dark' || (!theme && true)) { // defaults to true (dark)\r\n                document.documentElement.classList.add('dark');\r\n            } else if (theme === 'light') {\r\n                document.documentElement.classList.remove('dark');\r\n            }\r\n        })();\r\n    </script><link rel=\"stylesheet\" href=\"/assets/css/input.css\"><link rel=\"preload\" href=\"/assets/fonts/noto-kufi-arabic-regular.woff2\" as=\"font\" type=\"font/woff2\" crossorigin><link rel=\"preload\" href=\"/assets/fonts/noto-kufi-arabic-bold.woff2\" as=\"font\" type=\"font/woff2\" crossorigin>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
